apiVersion: v2
name: telemetry-management
description: Telemetry Management service for Smart Home.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "16.0.1"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
